services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE   # Quitar en macOS (no existe)
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVERURL=5.224.225.87 # IP publica
      - SERVERPORT=51820
      - PEERS=10 # Num clientes
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0/16 #Red aislada
    volumes:
      - ./wireguard:/config
      # - /root/wireguard:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    # En macOS a veces ayuda añadir esto:
    # privileged: true                     # ← Solo en macOS y Windows

